version: 1.1.{build}

configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

skip_tags: true

cache:
  - packages\OpenCover*
  - packages\coveralls.io*\tools

environment:
  COVERALLS_REPO_TOKEN:
    secure: fm7taq4Ao1Fu09OLM+KKQJlLwUsmDq9801njnfwhSTadQ3eAcYx+meW/LxK/4Mq0

nuget:
  disable_publish_on_pr: true

install:
- nuget restore

build:
  project: coveralls.net.sln
  verbosity: normal

after_build:
- ps: .\package.ps1

artifacts:
- path: coveralls.net/package/*.nupkg
  name: package

after_test:
- ps: .\coverage.ps1

deploy:
- provider: NuGet
  api_key:
    secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61
  on:
    branch: master