version: 1.3.3

skip_tags: true

configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  disable_publish_on_pr: true

install:
  - nuget restore

build:
  project: coveralls.net.sln
  verbosity: quiet

before_deploy:
  - cd coveralls.net\package
  - nuget pack coveralls.net.nuspec -Version "1.3.3"
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
- provider: NuGet
  api_key:
    secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61
- provider: GitHub
  release: v$(appveyor_build_version)
  auth_token:
    secure: WRmagJhEEWkaFh1uKE4V2ppO8s6SxDDX4GKUbsphUuAeutB/B/H5OJp/g/V3lNiX
  artifact: /.*\.nupkg/
  draft: false
  prerelease: true