-
  branches:
    only:
      - production

  version: 1.2.{build}

  configuration: Release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  nuget:
    disable_publish_on_pr: true

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: quiet

  before_deploy:
    - cd coveralls.net\package
    - nuget pack coveralls.net.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  deploy:
  - provider: NuGet
    api_key:
      secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61

-
  branches:
    only:
      - master

  version: 1.2.{build}-beta

  configuration: Debug

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  cache:
    - packages

  nuget:
    disable_publish_on_pr: true

  environment:
    COVERALLS_REPO_TOKEN:
      secure: NobuuqxquNHmXlTnejNYN8U0qJNbOP5cNyEOSN6dYN5SPFZLBzAjQY6/0/9WhnRu

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: minimal

  test_script:
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[Coveralls*]*" -target:"nunit-console.exe" -targetargs:"/noshadow /domain:single Coveralls.Tests\bin\%CONFIGURATION%\Coveralls.Tests.dll" -output:coverage.xml

  after_test:
    - coveralls.net\package\tools\coveralls.net.exe --opencover coverage.xml

  before_deploy:
    - cd coveralls.net\package
    - nuget pack coveralls.net.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  deploy:
  - provider: NuGet
    api_key:
      secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61

-
  branches:
    only:
      - analyze

  version: 1.2.{build}-alpha

  configuration: Debug

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  cache:
    - packages

  nuget:
    disable_publish_on_pr: true

  environment:
    CoverityProjectToken:
      secure: d8DfQb7jeKo/QQGV1bv10ba8+8b0HstE8QFt1C0kV6w=

  install:
    - nuget restore

  build_script:
  - ps: |
      $buildCmd = "msbuild.exe"
      $buildArgs = @("/m", "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll")    
      C:\Tools\Coverity\bin\cov-build.exe --dir cov-int $buildCmd $buildArgs  
  - cmd: nuget install PublishCoverity -ExcludeVersion
  - cmd: PublishCoverity\PublishCoverity.exe compress -o coverity.zip -i cov-int
  - cmd: PublishCoverity\PublishCoverity.exe publish -z coverity.zip -r jdeering/coveralls.net -t %CoverityProjectToken% -e jason@deering.me --nologo