version: 1.1.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

skip_tags: true

nuget:
  disable_publish_on_pr: true

build:
  project: coveralls.net.sln
  verbosity: minimal

after_build:
- msbuild coveralls.net.metaproj /t:Package

artifacts:
- path: coveralls.net/package/*.nupkg
  name: package
after_test:
- msbuild coveralls.net.metaproj /t:Package
  
deploy:
- provider: NuGet
  api_key:
    secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61
  on:
    branch: master