-
  branches:
    only:
      - production

  version: 1.1.{build}

  configuration: Release

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  nuget:
    disable_publish_on_pr: true

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: quiet

  before_deploy:
    - cd coveralls.net\package
    - nuget pack coveralls.net.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  deploy:
  - provider: NuGet
    api_key:
      secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61

-
  branches:
    only:
      - master

  version: 1.1.{build}-beta

  configuration: Debug

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  cache:
    - packages

  nuget:
    disable_publish_on_pr: true

  environment:
    COVERALLS_REPO_TOKEN:
      secure: 7slhRtUVG7VaqcwNQjD5Kph7NTudBTPrGZswajNcSP9iA9QZIVNI38wm1pfc3/vZ

  install:
    - nuget restore

  build:
    project: coveralls.net.sln
    verbosity: minimal

  test_script:
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[Coveralls*]*" -target:"nunit-console.exe" -targetargs:"/noshadow /domain:single Coveralls.Tests\bin\%CONFIGURATION%\Coveralls.Tests.dll" -output:coverage.xml

  after_test:
    - coveralls.net\package\tools\coveralls.net.exe --repo-token 7tmi9FWyPENcNM664ozTrC2vgLe7GLnI9 --opencover coverage.xml

  before_deploy:
    - cd coveralls.net\package
    - nuget pack coveralls.net.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  deploy:
  - provider: NuGet
    api_key:
      secure: 2fcbcVHpBbBN9Q9vnWfQaWBpTn0H/5Y10cBMVD1XJuJv5Tcyvcr63lsdAMHJyg61