version: 0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

skip_tags: true

nuget:
  disable_publish_on_pr: true

build:
  project: Symitar.sln
  verbosity: minimal
